# cran packages
library(drake)
library(tidyverse)
library(haven)
library(furrr)
library(raster)
library(fasterize)
library(rgdal)
library(patchwork)
library(here)
library(readxl)
library(sf)
library(acs)
library(slider)

# non-cran packages
library(hydro) # devtools::install_github("matthewkling/hydro")

# namespace conflict resolution
library(conflicted)
conflict_prefer("select", "dplyr", quiet = T)
conflict_prefer("filter", "dplyr", quiet = T)
conflict_prefer("gather", "tidyr", quiet = T)
conflict_prefer("extract", "raster", quiet = T)
conflict_prefer("lag", "dplyr", quiet = T)
conflict_prefer("values", "raster", quiet = T) 
conflict_prefer("setdiff", "base", quiet = T) 
conflict_prefer("annotate", "ggplot2", "patchwork", quiet = T) 
conflict_prefer("plan", "future", quiet = T)
conflict_prefer("gather", "tidyr", quiet = T)
conflict_prefer("expand", "tidyr", quiet = T)
